# Generated by Django 6.0.5 on 2026-05-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionrecord',
            old_name='activity_type',
            new_name='emission_record',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='record',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='category',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='company',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='normalized_unit',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='original_unit',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='source',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='suspicious',
        ),
        migrations.RemoveField(
            model_name='source',
            name='company',
        ),
        migrations.RemoveField(
            model_name='source',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='source',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='source',
            name='source_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
