# Generated by Django 6.0.5 on 2026-05-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0002_rename_activity_type_emissionrecord_emission_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='scope',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='source_type',
            field=models.CharField(default='SAP', max_length=100),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
