# Generated by Django 6.0.5 on 2026-05-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0003_emissionrecord_scope_emissionrecord_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='company_name',
            field=models.CharField(default='Demo Company', max_length=255),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='locked_for_audit',
            field=models.BooleanField(default=False),
        ),
    ]
